### ISSUE TITLE
p-value and statistics

### ISSUE THREAD

**Issue by Poocee** [sachsmc/ggkm#12]
Hi @sachsmc,

thanks for this useful package!
I wonder if there is a possibility to integrate the statistical p-value on the graph.
Thanks in advance.
Stefano

**Comment by sachsmc** [comment]
Yes, you can use the annotate function from ggplot2 to add p-values to a graph. 

See examples here: https://ggplot2.tidyverse.org/reference/annotate.html#ref-examples
