### ISSUE TITLE
Using a Stepped version of ribbon for the confidence bands ?

### ISSUE THREAD

**Issue by smouksassi** [sachsmc/ggkm#6]
Hi thanks for the nice and only real extension to ggplot to include a KM "stat". I have an issue which is probably related to nousing a stepped ribbon for the confidence intervals. This result in sometimes truncating the ribbon see below the ecog 2 curve while the ecog 3 curve is not shown at all it only appears in the legend  :
Compare:

``` r
library(survival)
library(rms)
lung$SurvObj <- with(lung, Surv(time, status == 2))
km.by.ecog <- npsurv(SurvObj ~ ph.ecog , data = lung)
survplot(fit  = km.by.ecog, conf = c("bands"))
```

rms survplot output
![rmsplot](https://cloud.githubusercontent.com/assets/5131281/16953378/c9c56bb2-4d9a-11e6-9fcd-8481623c6412.png)

``` r
ggplot(lung, aes(time = time, status = ifelse(
          status == 2,1,0),col=as.factor(ph.ecog ),fill=as.factor(ph.ecog ))) +
 geom_km(fill="transparent")+ stat_km(geom="ribbon",alpha=0.1,color="black")+ # this to make the legend include the fill
          geom_kmticks() 
```

geom_km /stat_km output (ecog 2 ribbon truncated, ecog 3 not shown):
![stat_kmplot](https://cloud.githubusercontent.com/assets/5131281/16953032/939b0642-4d99-11e6-92f5-54aa0e50c48a.png)

A potential solution is to use code from but it is only a stat we might need to add a "step_ribbon" geom:
https://groups.google.com/forum/?fromgroups=#!topic/ggplot2/9cFWHaH1CPs

**Comment by sachsmc** [comment]
Thanks for pointing this out, I will work on adding it into the package.

**Comment by smouksassi** [comment]
```
                                                                                  ‎ggalt has it already maybe just import it?https://github.com/hrbrmstr/ggaltThank you for the followup.Samer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Michael SachsSent: Tuesday, August 2, 2016 08:42To: sachsmc/ggkmReply To: sachsmc/ggkmCc: Samer Mouksassi; AuthorSubject: Re: [sachsmc/ggkm] Using a Stepped version of ribbon for the confidence bands ? (#6)Thanks for pointing this out, I will work on adding it into the package. 
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sachsmc** [comment]
Try it out now using the master branch. `install_github("sachsmc/ggkm")`  The grey line that appears is for the single case where ph.ecog is NA. 

![fix](https://cloud.githubusercontent.com/assets/5464185/17358327/954840c6-5961-11e6-815a-793219ed27c0.png)
