### ISSUE TITLE
stat_km fails in some situations

### ISSUE THREAD

**Issue by smouksassi** [sachsmc/ggkm#7]
Hi ,
I am still testing the new version you provided in some situation I get errors
the df providing the error is attached as a zip.
[df.zip](https://github.com/sachsmc/ggkm/files/426129/df.zip)

``` r
df <-read.csv("df.csv")
p1<-  ggplot(df, aes(time=time, status = status, color = factor(sex)))
 p1 +stat_km()
```

Warning message:
Computation failed in `stat_km()`:
arguments imply differing number of rows: 201, 202 

``` r
p1 + stat_km(trans = "cumhaz") # works no error
p1 + stat_km(trans = "cumhaz")+ scale_x_log10()# works
p1 + stat_km(trans = "cumhaz")+ scale_y_log10() # somehow the log axis does not apply to the ribbons
```

please let me know if you need more info about these bugs

**Comment by schelhorn** [comment]
I have the same issue; seems to be related to SE computation since the problem goes away with `geom_km(se=FALSE)` (but then there are no confidence bands). On a related note, how exactly can desired confidence levels be specified? `geom_km(conf.int=0.95)` does not work.

**Comment by sachsmc** [comment]
@smouksassi @schelhorn I fixed these and some other issues by moving the confidence bands into separate stat and geom. The new syntax is as follows (also see the updated readme):

```
df <- read.csv("~/../Downloads/df.csv")
p1<-  ggplot(df, aes(time=time, status = status, color = factor(sex)))
p1 +stat_km() + geom_kmband()
p1 + stat_km(trans = "cumhaz") # works no error
p1 + stat_km(trans = "cumhaz")+ scale_x_log10()# works
p1 + stat_km(trans = "cumhaz")+ geom_kmband(trans = "cumhaz") + scale_y_log10() #works 
```
